remote_theme: pages-themes/midnight@v0.2.0
title: IIIF Buchanan Fellows Project
description: Website to display the work of the 2023 Buchanan Fellowship project to learn how to use IIIF to display artwork images
